# Generated by Django 4.2.11 on 2024-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Historyzhanshi_table",
            fields=[
                ("name", models.CharField(max_length=20, verbose_name="用户名")),
                ("uid", models.IntegerField(verbose_name="用户id")),
                ("item_name", models.CharField(max_length=100, verbose_name="电影名称")),
                (
                    "bastags",
                    models.CharField(blank=True, max_length=60, verbose_name="标签"),
                ),
                ("action", models.CharField(max_length=5, verbose_name="行为")),
                (
                    "time",
                    models.DateTimeField(
                        blank=True, default="2008-12-12 12:12:00", verbose_name="点击时间"
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        blank=True, primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
            ],
            options={"verbose_name_plural": "行为信息", "db_table": "historyzhanshi",},
        ),
        migrations.CreateModel(
            name="User_table",
            fields=[
                ("username", models.CharField(max_length=20, verbose_name="用户名")),
                ("password", models.CharField(max_length=20, verbose_name="密码")),
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="用户id"
                    ),
                ),
                ("token", models.CharField(max_length=255, null=True)),
                (
                    "email",
                    models.CharField(max_length=40, null=True, verbose_name="邮箱"),
                ),
                (
                    "phoneNumber",
                    models.CharField(max_length=11, null=True, verbose_name="电话"),
                ),
                ("sex", models.CharField(max_length=5, null=True, verbose_name="性别")),
            ],
            options={"verbose_name_plural": "用户信息", "db_table": "rs_user",},
        ),
    ]
